language: c

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode8.3

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
