language: c

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode8.3

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install 3.4.2; pyenv global 3.4.2; PATH=$(pyenv root)/shims:$PATH; fi
  - curl https://bootstrap.pypa.io/get-pip.py | python3.4 - --user
  - python3.4 -m pip install --user setuptools wheel

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
