language: c

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode8.3

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl https://www.python.org/ftp/python/3.4.4/python-3.4.4-macosx10.6.pkg -o python.pkg; sudo installer -pkg python.pkg -target /; fi
  - curl https://bootstrap.pypa.io/get-pip.py | python3.4 - --user
  - python3.4 -m pip install --user setuptools wheel

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
